import { Router } from "express";

import healthRouter from "./health";
import leadsRouter from "./leads";
import usersRouter from "./users";
import propertiesRouter from "./properties";
import storageRouter from "./storage";
import connectedAccountsRouter from "./connectedAccounts";
import whatsappRouter from "./whatsapp";
import leadSyncRouter from "./leadSync";
import activitiesRouter from "./activities";
import aiRouter from "./ai";
import automationsRouter from "./automations";
import analyticsRouter from "./analytics";
import dealsRouter from "./deals";
import teamMembersRouter from "./teamMembers";
import documentsRouter from "./documents";
import appointmentsRouter from "./appointments";
import settingsRouter from "./settings";
import notificationsRouter from "./notifications";
import dealersRouter from "./dealers";
import organizationsRouter from "./organizations";
import paymentRequestsRouter from "./paymentRequests";
import plansRouter from "./plans";
import auditLogsRouter from "./auditLogs";
import addonsRouter from "./addons";
import facebookRouter from "./facebook";
import invitationsRouter from "./invitations";
import orgMembersRouter from "./orgMembers";
import supportRouter from "./support";
import privacyRouter from "./privacy";
import onboardingRouter from "./onboarding";

const router = Router();

// mount with explicit prefixes (IMPORTANT)
router.use("/health", healthRouter);
router.use("/leads", leadsRouter);
router.use("/users", usersRouter);
router.use("/properties", propertiesRouter);
router.use("/storage", storageRouter);
router.use("/connected-accounts", connectedAccountsRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/lead-sync", leadSyncRouter);
router.use("/activities", activitiesRouter);
router.use("/ai", aiRouter);
router.use("/automations", automationsRouter);
router.use("/analytics", analyticsRouter);
router.use("/deals", dealsRouter);
router.use("/team-members", teamMembersRouter);
router.use("/documents", documentsRouter);
router.use("/appointments", appointmentsRouter);
router.use("/settings", settingsRouter);
router.use("/notifications", notificationsRouter);
router.use("/dealers", dealersRouter);
router.use("/organizations", organizationsRouter);
router.use("/payment-requests", paymentRequestsRouter);
router.use("/plans", plansRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/addons", addonsRouter);
router.use("/facebook", facebookRouter);
router.use("/invitations", invitationsRouter);
router.use("/org-members", orgMembersRouter);
router.use("/support", supportRouter);
router.use("/privacy", privacyRouter);
router.use("/onboarding", onboardingRouter);

export default router;