import { pgTable, serial, varchar, integer, timestamp } from "drizzle-orm/pg-core";
import { organizations } from "./organizations";

export const rolePermissions = pgTable("role_permissions", {
  id: serial("id").primaryKey(),
  organizationId: integer("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  roleName: varchar("role_name", { length: 100 }).notNull(),
  resource: varchar("resource", { length: 100 }).notNull(),
  action: varchar("action", { length: 50 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export type RolePermission = typeof rolePermissions.$inferSelect;
export type NewRolePermission = typeof rolePermissions.$inferInsert;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Array<{ resource: string; action: string }>> = {
  admin: [
    { resource: "dashboard", action: "view" },
    { resource: "leads", action: "view" },
    { resource: "leads", action: "create" },
    { resource: "leads", action: "edit" },
    { resource: "leads", action: "delete" },
    { resource: "messages", action: "view" },
    { resource: "messages", action: "create" },
    { resource: "messages", action: "edit" },
    { resource: "messages", action: "delete" },
    { resource: "properties", action: "view" },
    { resource: "properties", action: "create" },
    { resource: "properties", action: "edit" },
    { resource: "properties", action: "delete" },
    { resource: "dealers", action: "view" },
    { resource: "dealers", action: "create" },
    { resource: "dealers", action: "edit" },
    { resource: "dealers", action: "delete" },
    { resource: "analytics", action: "view" },
    { resource: "ai_intelligence", action: "view" },
    { resource: "ai_intelligence", action: "create" },
    { resource: "automations", action: "view" },
    { resource: "automations", action: "create" },
    { resource: "automations", action: "edit" },
    { resource: "automations", action: "delete" },
    { resource: "team", action: "view" },
    { resource: "team", action: "create" },
    { resource: "team", action: "edit" },
    { resource: "team", action: "delete" },
    { resource: "deals", action: "view" },
    { resource: "deals", action: "create" },
    { resource: "deals", action: "edit" },
    { resource: "deals", action: "delete" },
    { resource: "documents", action: "view" },
    { resource: "documents", action: "create" },
    { resource: "documents", action: "edit" },
    { resource: "documents", action: "delete" },
    { resource: "calendar", action: "view" },
    { resource: "calendar", action: "create" },
    { resource: "calendar", action: "edit" },
    { resource: "calendar", action: "delete" },
    { resource: "settings", action: "view" },
    { resource: "settings", action: "edit" },
  ],
  manager: [
    { resource: "dashboard", action: "view" },
    { resource: "leads", action: "view" },
    { resource: "leads", action: "create" },
    { resource: "leads", action: "edit" },
    { resource: "leads", action: "delete" },
    { resource: "messages", action: "view" },
    { resource: "messages", action: "create" },
    { resource: "messages", action: "edit" },
    { resource: "properties", action: "view" },
    { resource: "properties", action: "create" },
    { resource: "properties", action: "edit" },
    { resource: "dealers", action: "view" },
    { resource: "dealers", action: "create" },
    { resource: "dealers", action: "edit" },
    { resource: "analytics", action: "view" },
    { resource: "ai_intelligence", action: "view" },
    { resource: "ai_intelligence", action: "create" },
    { resource: "automations", action: "view" },
    { resource: "team", action: "view" },
    { resource: "deals", action: "view" },
    { resource: "deals", action: "create" },
    { resource: "deals", action: "edit" },
    { resource: "documents", action: "view" },
    { resource: "documents", action: "create" },
    { resource: "documents", action: "edit" },
    { resource: "calendar", action: "view" },
    { resource: "calendar", action: "create" },
    { resource: "calendar", action: "edit" },
    { resource: "settings", action: "view" },
  ],
  agent: [
    { resource: "dashboard", action: "view" },
    { resource: "leads", action: "view" },
    { resource: "leads", action: "create" },
    { resource: "leads", action: "edit" },
    { resource: "messages", action: "view" },
    { resource: "messages", action: "create" },
    { resource: "properties", action: "view" },
    { resource: "dealers", action: "view" },
    { resource: "documents", action: "view" },
    { resource: "documents", action: "create" },
    { resource: "calendar", action: "view" },
    { resource: "calendar", action: "create" },
    { resource: "calendar", action: "edit" },
  ],
  custom: [
    { resource: "dashboard", action: "view" },
    { resource: "leads", action: "view" },
    { resource: "messages", action: "view" },
  ],
};
